apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-config
  namespace: nagp-assignment-pg
data:
  data.sql: |-
    CREATE DATABASE IF NOT EXISTS sampleDB;
    
    USE sampleDB;

    CREATE TABLE IF NOT EXISTS departments (
        department_id BINARY(16) PRIMARY KEY,
        department_name VARCHAR(255) NOT NULL UNIQUE
    );

    CREATE TABLE IF NOT EXISTS employees (
        employee_id BINARY(16) PRIMARY KEY,
        first_name VARCHAR(255) NOT NULL,
        last_name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE,
        mobile_number VARCHAR(255) NOT NULL UNIQUE,
        employee_type VARCHAR(255) NOT NULL,
        department_id BINARY(16),
        created_at TIMESTAMP NOT NULL,
        updated_at TIMESTAMP NOT NULL
    );
