apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
  namespace: service-prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/disks
  persistentVolumeReclaimPolicy: Retain