apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  namespace: nagp-assignment-pg
  labels:
    app: mysql-db
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
      type: db
  serviceName: "mysql-db-service"
  template:
    metadata:
      labels:
        app: mysql-db
        type: db
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: initdb
          configMap:
            name: db-init-config
  updateStrategy:
    type: RollingUpdate