apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
  namespace: nagp-assignment-pg
spec:
  selector:
    app: mysql-db
    type: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306