apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-service-deployment
  namespace: nagp-assignment-pg
  labels:
    app: spring-boot-service
    type: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spring-boot-service
      type: backend
  template:
    metadata:
      name: spring-boot-service-pod
      labels:
        app: spring-boot-service
        type: backend
    spec:
      containers:
        - name: spring-boot-service-container
          image: getabhay/simple-microservice:latest
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_URL
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_USERNAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5