name: CD - Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: demo-env

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Dockerrun
        run: |
          cp Dockerrun.aws.json Dockerrun-final.json
          sed -i "s|REPLACE_IMAGE|${{ secrets.ECR_REPOSITORY_URI }}:latest|" Dockerrun-final.json
          mv Dockerrun-final.json Dockerrun.aws.json

      - name: Validate JSON
        run: python -m json.tool Dockerrun.aws.json

      - name: Zip
        run: zip deploy.zip Dockerrun.aws.json
      
      - name: List zip content (DEBUG)
        run: unzip -l deploy.zip

      - name: Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: v-${{ github.run_number }}-${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
